version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bookmarked-postgres
    environment:
      POSTGRES_USER: bookmarked
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookmarked_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: bookmarked-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data: