name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST_PORT: ${{ secrets.POSTGRES_HOST_PORT }}
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      NEO4J_AUTH: ${{ secrets.NEO4J_AUTH }}
      NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      NEO4J_HTTP_HOST_PORT: ${{ secrets.NEO4J_HTTP_HOST_PORT }}
      NEO4J_BOLT_HOST_PORT: ${{ secrets.NEO4J_BOLT_HOST_PORT }}
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and Test with Maven
      run: mvn -B clean verify --file bookmarked-api/pom.xml